name: Tests on windows

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - main
#       - develop
#   pull_request:
#     branches:
#       - main
#       - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        php: [8.1]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Install for Windows
        if: runner.os == 'Windows'
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop install 7zip imagemagick ghostscript@9.54.0 ffmpeg
          php -i | find "Thread Safety"
          php -i | grep "Architecture"
          Invoke-WebRequest -Uri https://windows.php.net/downloads/pecl/releases/rar/4.2.0/php_rar-4.2.0-8.1-nts-vs16-x64.zip -OutFile php_rar.zip
          7z x php_rar.zip -ophp_rar
          cd php_rar
          ls
          php --ini
          gs
        shell: powershell

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      # - name: Add rar extension
      #   if: runner.os == 'Linux' || runner.os == 'macOS'
      #   run: |
      #     git clone https://github.com/cataphract/php-rar
      #     cd php-rar
      #     phpize
      #     ./configure
      #     sudo make
      #     sudo make install
      #     pecl_path=$(pecl config-get ext_dir)
      #     phpini_path=$(php -i | grep /.+/php.ini -oE)
      #     sudo cp ./modules/rar.so $pecl_path
      #     sudo echo "extension=rar.so" > $phpini_path

      # - name: Check extension rar
      #   run: php -m | grep rar

      - name: Check extension imagick
        run: php -m | grep imagick

      - name: Execute tests
        run: vendor/bin/pest
