name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: [8.2, 8.1]
        stability: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Install
        run: |
          echo $RUNNER_OS;
          if [ "$RUNNER_OS" == "Linux" ]; then
            apt install important_linux_software
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install important_windows_software
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      # - name: Add rar extension
      #   run: |
      #     sudo apt-get install -y unrar
      #     sudo apt-get install -y libunrar-dev
      #     git clone https://github.com/cataphract/php-rar
      #     cd php-rar
      #     phpize
      #     ./configure
      #     sudo make
      #     sudo make install
      #     pecl_path=$(pecl config-get ext_dir)
      #     phpini_path=$(php -i | grep /.+/php.ini -oE)
      #     sudo cp ./modules/rar.so $pecl_path
      #     sudo echo "extension=rar.so" > $phpini_path

      - name: Execute tests
        run: vendor/bin/pest --coverage

      - name: Execute tests
        run: vendor/bin/phpstan analyse --memory-limit=2G

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false
