name: Tests on unix

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install p7zip-full ghostscript imagemagick
          sudo apt install -y unrar
          sudo apt install -y libunrar-dev
          sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: imagick, zip, fileinfo, bz2
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Add rar extension
        run: |
          git clone https://github.com/cataphract/php-rar
          cd php-rar
          phpize
          ./configure
          sudo make
          sudo make install
          pecl_path=$(pecl config-get ext_dir)
          phpini_path=$(php -i | grep /.+/php.ini -oE)
          sudo cp ./modules/rar.so $pecl_path
          sudo echo "extension=rar.so" > $phpini_path

      - name: Check extension rar
        run: php -m | grep rar

      - name: Check extension imagick
        run: php -m | grep imagick

      - name: Execute tests
        run: vendor/bin/pest

      - name: on Linux run phpstan
        run: vendor/bin/phpstan analyse --memory-limit=2G
        shell: bash
